name = "vapour"
version = "0.1.0"
description = "Type-safe Gleam bindings for steamworks-ffi-node - 1:1 Steam API integration"
licences = ["MIT"]
repository = { type = "github", user = "renatillas", repo = "vapour" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/renatillas" },
]

target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
